# Generated by Django 5.0.14 on 2026-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=20)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('queue', models.CharField(blank=True, max_length=50)),
                ('duration', models.IntegerField(default=0)),
                ('recording_url', models.URLField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
